fix printf

diff --git a/bin/urldiff b/bin/urldiff
--- a/bin/urldiff
+++ b/bin/urldiff
@@ -28,16 +28,13 @@
 # -- FUNCTIONS.
 
 Urldiff::CheckConnection ()
-if
-        ! command ping -c1 debian.org >/dev/null 2>&1
-then
-        if
-                ! command wget -O - debian.org >/dev/null 2>&1
-        then
-                builtin printf '%s\n' "ERROR We are probably offline." 1>&2
+{
+        command ping -c1 debian.org >/dev/null 2>&1 ||
+        command wget -O - debian.org >/dev/null 2>&1 || {
+                builtin printf '%s\n' "ERROR We are probably offline" 1>&2
                 builtin exit 79
-        fi
-fi
+        }
+}
 
 Urldiff::CheckUrl ()
 {
@@ -85,8 +82,7 @@ Urldiff::CheckUrl ()
                         command w3m -dump -T text/html > "$onlineascii" < "$onlinehtml"
                 else
                         command rm -- "$onlinehtml"
-                        builtin printf '%s\n' \
-                                "FAIL $(command date +%Y-%m-%d_%H:%M) URL: ${url} unattainable" 1>&3
+                        builtin printf 'FAIL %(%Y-%m-%d_%H:%M)T URL: %s unattainable\n' -1 "$url" 1>&3
                         builtin return 1
                 fi
 
@@ -102,22 +98,20 @@ Urldiff::CheckUrl ()
                 if
                         command cmp -s "$onlineascii" "$localascii"
                 then
-                        builtin printf '%s\n' \
-                                "OLD $(command date +%Y-%m-%d_%H:%M) URL: ${url}" 1>&3
+                        builtin printf 'OLD %(%Y-%m-%d_%H:%M)T URL: %s\n' -1 "$url" 1>&3
                 else
                         Urldiff::Diff
-                        builtin printf '%s\n' \
-                                "NEW $(command date +%Y-%m-%d_%H:%M) URL: ${url}" \
-                                "    file://${difftxt}"  \
-                                "    file://${localhtml}" \
-                                "    file://${localascii}" 1>&3
+                        builtin printf 'NEW %(%Y-%m-%d_%H:%M)T URL: %s\n\tfile://%s\n\tfile://%s\n\tfile://%s\n' -1 \
+                                "$url" \
+                                "$difftxt"  \
+                                "$localhtml" \
+                                "$localascii" 1>&3
                 fi
 
                 command mv -- "$onlinehtml" "$localhtml"
                 command mv -- "$onlineascii" "$localascii"
         else
-                builtin printf '%s\n' \
-                        "FAIL $(command date +%Y-%m-%d_%H:%M) URL: ${url} does not match" 1>&3
+                builtin printf 'FAIL %(%Y-%m-%d_%H:%M)T URL: %s does not match' -1 "$url" 1>&3
                 builtin return 1
         fi
 }
@@ -242,13 +236,13 @@ Urldiff::Main ()
         then
                 [[ $output =~ (-nv|-v) ]] && {
                         command tput bold setaf 7
-                        builtin printf '%s\n' 'Checking...'
+                        builtin printf '%s\n' 'Checking ...'
                         command tput sgr0
                 }
 
                 exec 3>>"$reportnew"
                 command xargs -a "$urllist" -n 1 -P 8 \
-                        -i bash -c 'Urldiff::CheckUrl $@' _ {} +
+                        -i bash -c 'Urldiff::CheckUrl "$@"' _ {} +
                 exec 3<&-
 
                 if
@@ -266,7 +260,7 @@ Urldiff::Main ()
                         command sed -n 'p' "$reportnew"
                 }
 
-                (( mail == 1 )) && {
+                (( mail )) && {
                         command mail -s \
                                 "[URLDIFF] Report" "$mailto" \
                         < "$reportnew"
@@ -274,12 +268,12 @@ Urldiff::Main ()
 
                 command mv -- "$reportnew" "$reportold"
         else
-                builtin printf '%s\n' "ERROR No url list to look for." 1>&2
+                builtin printf '%s\n' "ERROR No url list to look for" 1>&2
                 builtin exit 80
         fi
 }
 
-Urldiff::Version () { builtin printf 'v%s\n' "0.2.1" ; }
+Urldiff::Version () { builtin printf 'v%s\n' "0.2.2" ; }
 
 # -- MAIN.
 
